### ISSUE TITLE
Conflict with decocraft 2?

### ISSUE THREAD

**Issue by beanaboston** [Leviathan-Studio/CraftStudioAPI#38]
## Expected Behavior
The game should load

## Current Behavior
The game crashes while trying to load

## Possible Solution
dunno. I'm just trying to play with the mod.

## Steps to Reproduce 
1. install version 2.6.0 of decocraft2 for mc version 1.12.2
2. install versions of stuff from below
3. attempt to launch game

## Context
Trying to load game.

## Crash Report
https://pastebin.com/sNABJV6T

## Your Environment
* Version of the api used: 1.0.0.93-mc1.12-alpha
* Version of forge used: 14.23.4.2707
* Link to your project: N/A

**Comment by Timmypote** [comment]
Does it work without the CraftStudioAPI ? Cause I don't see anything that say it's our mod that cause the crash or anything that would cause a conflict with Decocraft. The class "com/mia/craftstudio/IPackReaderCallback" is from Decocraft, the name might be confusing but that's because Decocraft as it's own code to import CraftStudio ressources in Minecraft.
Furthermore,
	| State | ID             | Version      | Source                                | Signature                                |
	|:----- |:-------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| UC    | minecraft      | 1.12.2       | minecraft.jar                         | None                                     |
	| UC    | mcp            | 9.42         | minecraft.jar                         | None                                     |
	| UC    | FML            | 8.0.99.99    | forge-1.12.2-14.23.4.2707.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge          | 14.23.4.2707 | forge-1.12.2-14.23.4.2707.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | craftstudioapi | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar | None                                     |
	| U     | props          | 2.6.0        | Decocraft-2.6.0_1.12.2.jar            | None                                     |

you can see that craftstudioapi is constructed normaly and Decocraft has a problem.
So I think you should ask to the modders of Decocraft.

PS: Thank for the completeness of your report :) I'm going to have a deeper look at that so I stop having this issue repported.

**Comment by beanaboston** [comment]
Alright thanks. I'll report it to the DecoCraft devs later today. See if
they have any idea. Thanks for the reply.

**Comment by Timmypote** [comment]
Yup, not our fault and not the fault of Decocraft's modders. It seems that you're missing some depedencies according to [this page](https://minecraft.curseforge.com/projects/decocraft2/issues/1652). As you can see [here](https://minecraft.curseforge.com/projects/decocraft2/relations/dependencies), Decocraft need a lib, which is not in your mod list.
I'm closing the issue, and hope people will look here before reporting this bug.
